marker_based_localizer:
  ros__parameters:
    marker_objects:
      object_1:
        object_id: 507
        translation: [0.6, 0.0, 0.0]
        rotation: [-0.5, 0.5, -0.5, 0.5]
      object_2:
        object_id: 508
        translation: [0.0, 0.0, 0.6]
        rotation: [0.5, -0.5, 0.5, -0.5]
